# LASS_INCLUDE_DIR = lass.h
# LASS_LIBRARIES = liblass.so
# LASS_FOUND = true if cat is found

IF(LASS_INCLUDE_DIRS)
  FIND_PATH(LASS_INCLUDE_DIR lass.h  ${LASS_INCLUDE_DIRS})
  FIND_LIBRARY(LASS_LIBRARIES lass ${LASS_LIBRARY_DIRS})
ENDIF(LASS_INCLUDE_DIRS)


SET(LASS_FOUND FALSE)
IF(LASS_INCLUDE_DIR)
  MESSAGE(STATUS "LASS_INCLUDE_DIR=${LASS_INCLUDE_DIR}")
  MESSAGE(STATUS "LASS_LIBRARIES=${LASS_LIBRARIES}")
  SET(LASS_FOUND TRUE)
ENDIF(LASS_INCLUDE_DIR)

MARK_AS_ADVANCED(
   LASS_INCLUDE_DIR
   LASS_LIBRARIES
   LASS_FOUND
)

