#!/usr/bin/python

from os import system
import sys

basefname=sys.argv[1]

if basefname=="":
	basefname='base'


def run(seed,bg):
	cfgfname=basefname+'_'+str(seed)+'.cfg'
        input=open(basefname+'.cfg')
        output=open(cfgfname,'w')
        rstext = "basic_seed=seed"
        rtext = "basic_seed="+str(seed)
        for s in input.xreadlines():
                output.write(s.replace(rstext,rtext))
        input.close()
        output.close()
	if bg==1:
        	system('time mhdc3dl_lss '+cfgfname+' & ')
	else:
		system('time mhdc3dl_lss '+cfgfname)

for i in range(100,200,4):
	for j in range(0,3):
		run(i+j,1)
	run(i+3,0)



